cluster: "./pbs-submit.py --depend \"{dependencies}\""
cluster-status: "pbs-status.py"
jobscript: "pbs-jobscript.sh"
jobs: {{cookiecutter.concurrent_jobs}}
immediate-submit: {{cookiecutter.immediate_submit}}
verbose: true
notemp: true
